# Generated by Django 2.1.7 on 2019-04-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190409_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='group_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
