# Generated by Django 2.1.5 on 2019-04-23 14:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190423_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='idea',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 23, 14, 25, 30, 383201, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 23, 14, 25, 30, 381209, tzinfo=utc)),
        ),
    ]
