# Generated by Django 2.1.7 on 2019-04-10 11:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190410_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 10, 11, 31, 11, 552921, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 10, 11, 31, 11, 551924, tzinfo=utc)),
        ),
    ]
