# Generated by Django 2.1.5 on 2019-04-11 03:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190410_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_category',
            name='project_tag',
        ),
        migrations.AddField(
            model_name='project_category',
            name='economy',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='project_category',
            name='it',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='project_category',
            name='life',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='project_category',
            name='politics',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='project_category',
            name='society',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='project_category',
            name='sport',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='idea',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 11, 3, 48, 0, 900391, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 11, 3, 48, 0, 894399, tzinfo=utc)),
        ),
    ]
