# Generated by Django 2.1.5 on 2019-04-23 14:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190423_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='idea',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 23, 14, 26, 11, 216114, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 23, 14, 26, 11, 214121, tzinfo=utc)),
        ),
    ]
