# Generated by Django 2.1.5 on 2019-04-13 07:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190411_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 13, 7, 45, 38, 233679, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='idea_keyword_list',
            name='idea_keyword_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 13, 7, 45, 38, 232683, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project_hit',
            name='project_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project_hit',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project_like',
            name='project_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project_like',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
