# Generated by Django 2.1.5 on 2019-04-15 02:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190413_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='idea_color',
            field=models.CharField(default='#ECF0F1', max_length=30),
        ),
        migrations.AlterField(
            model_name='idea',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 15, 2, 5, 0, 366672, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 15, 2, 5, 0, 365675, tzinfo=utc)),
        ),
    ]
