# Generated by Django 2.1.5 on 2019-04-18 05:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190415_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword_log',
            fields=[
                ('Keyword_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Keyword_log',
            },
        ),
        migrations.AlterField(
            model_name='idea',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 18, 5, 33, 25, 586139, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 18, 5, 33, 25, 584144, tzinfo=utc)),
        ),
    ]
