# Generated by Django 2.1.5 on 2019-04-30 01:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190430_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 30, 1, 43, 16, 881234, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_img',
            field=models.ImageField(default='https://s3.ap-northeast-2.amazonaws.com/static.hello-idea.com/static/not_found.gif', upload_to='project_img'),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 30, 1, 43, 16, 880238, tzinfo=utc)),
        ),
    ]
