# Generated by Django 2.1.5 on 2019-05-01 06:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190430_2147'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.AlterField(
            model_name='idea',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 1, 6, 58, 24, 30960, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_img',
            field=models.FileField(upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 1, 6, 58, 24, 28968, tzinfo=utc)),
        ),
    ]
