# Generated by Django 2.1.5 on 2019-05-02 03:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import server.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20190502_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 2, 3, 19, 55, 614840, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 2, 3, 19, 55, 613844, tzinfo=utc)),
        ),
    ]
