# Generated by Django 2.1.5 on 2019-05-04 02:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20190503_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='idea',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 4, 2, 39, 16, 684505, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 4, 2, 39, 16, 682511, tzinfo=utc)),
        ),
    ]
