# Generated by Django 2.1.5 on 2019-05-04 02:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20190504_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='target_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='idea',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 4, 2, 40, 34, 998877, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 4, 2, 40, 34, 996879, tzinfo=utc)),
        ),
    ]
